In [1]:
!pip install -U transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.1/11.1 MB 41.5 MB/s eta 0:00:00
  Attempting uninstall: transformers
    Found existing installation: transformers 5.10.1
    Uninstalling transformers-5.10.1:
      Successfully uninstalled transformers-5.10.1


In [2]:
from google.colab import userdata
hf_token = userdata.get('HUGGING_FACE_API')

In [ ]:
# Use Pipeline as a high-level helper

from transformers import pipeline

pipe = pipeline("text-generation",model="openai-community/gpt2",token=hf_token)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [ ]:
prompt = "Explain machine learning in one sentence"
result = pipe(prompt)
print(result)

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': 'Explain machine learning in one sentence.\n\nHere\'s an example of a machine learning example.\n\nA machine learning example uses a collection of sentences consisting of several blocks. Each block is a dictionary consisting of the sentence, or data structure of the sentence, as described in the article. The dictionary contains words like "tongue, ball, dog," "meant by hand," "used to write" and "as a word." When the machine learns a block, the machine learns a number of rules. For example, a sentence can be changed from one block to another by using the expression "to read" or "to read a book." When the machine learns a sentence, it learns a number of rules to choose from: for example, "to read" means that the machine must only choose from "to read" if it can find "tongue, ball, dog" or "meant by hand."\n\nIn some cases, the machine learns a block when it is first able to learn it from the dictionary. For example, a machine learning example can learn a sentence of 

In [ ]:
print(result[0]['generated_text'])

Explain machine learning in one sentence.

Here's an example of a machine learning example.

A machine learning example uses a collection of sentences consisting of several blocks. Each block is a dictionary consisting of the sentence, or data structure of the sentence, as described in the article. The dictionary contains words like "tongue, ball, dog," "meant by hand," "used to write" and "as a word." When the machine learns a block, the machine learns a number of rules. For example, a sentence can be changed from one block to another by using the expression "to read" or "to read a book." When the machine learns a sentence, it learns a number of rules to choose from: for example, "to read" means that the machine must only choose from "to read" if it can find "tongue, ball, dog" or "meant by hand."

In some cases, the machine learns a block when it is first able to learn it from the dictionary. For example, a machine learning example can learn a sentence of "The word "meant by hand" is

In [ ]:
# Load model directly

from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained(
    "openai-community/gpt2",
    token=hf_token
)

model = AutoModelForCausalLM.from_pretrained(
    "openai-community/gpt2",
    token=hf_token
)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [ ]:
tokenizer

GPT2Tokenizer(name_or_path='openai-community/gpt2', vocab_size=50257, model_max_length=1024, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>'}, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
})

In [ ]:
model

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50257, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

## tokenizer

In [ ]:
# Word to tokenize
text = "unbelivable"

# Convert the text into token IDs and return them as PyTorch tensors
tokenized_output = tokenizer(text, return_tensors="pt")

# Display the complete tokenizer output dictionary
print("Tokenizer Output:")
print(tokenized_output)

# Extract and display the token IDs
token_ids = tokenized_output["input_ids"][0]
print("\nToken IDs:")
print(token_ids)

# Convert token IDs back to text and display the decoded result
decoded_text = tokenizer.decode(token_ids)
print("\nDecoded Text:")
print(decoded_text)

Tokenizer Output:
{'input_ids': tensor([[  403,  6667, 21911]]), 'attention_mask': tensor([[1, 1, 1]])}

Token IDs:
tensor([  403,  6667, 21911])

Decoded Text:
unbelivable


In [ ]:
for token_id in token_ids:
  print(f"{token_id} -> {tokenizer.decode([token_id])}")

403 -> un
6667 -> bel
21911 -> ivable


## AutoModelForCausalLM

In [ ]:
input_text = "The capital of France is"
inputs = tokenizer(input_text, return_tensors="pt").input_ids

print(inputs)

model(inputs)

tensor([[ 464, 3139,  286, 4881,  318]])


CausalLMOutputWithCrossAttentions(loss=None, logits=tensor([[[ -36.2874,  -35.0114,  -38.0794,  ...,  -40.5164,  -41.3760,
           -34.9194],
         [ -75.1021,  -75.6483,  -82.6827,  ...,  -82.5961,  -79.3913,
           -76.2687],
         [ -80.0968,  -78.6868,  -81.2341,  ...,  -83.7548,  -85.6541,
           -79.8042],
         [ -86.0084,  -86.4617,  -91.0184,  ...,  -98.6911,  -93.3734,
           -87.9286],
         [-108.9542, -108.9326, -112.5793,  ..., -118.3345, -113.1505,
          -110.3779]]], grad_fn=<UnsafeViewBackward0>), past_key_values=DynamicCache(layers=[DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer, DynamicLayer]), hidden_states=None, attentions=None, cross_attentions=None)

In [ ]:
model(inputs).logits

tensor([[[ -36.2874,  -35.0114,  -38.0794,  ...,  -40.5164,  -41.3760,
           -34.9194],
         [ -75.1021,  -75.6483,  -82.6827,  ...,  -82.5961,  -79.3913,
           -76.2687],
         [ -80.0968,  -78.6868,  -81.2341,  ...,  -83.7548,  -85.6541,
           -79.8042],
         [ -86.0084,  -86.4617,  -91.0184,  ...,  -98.6911,  -93.3734,
           -87.9286],
         [-108.9542, -108.9326, -112.5793,  ..., -118.3345, -113.1505,
          -110.3779]]], grad_fn=<UnsafeViewBackward0>)

In [ ]:
out = model(inputs).logits[0,-1]
tokenizer.decode(out.argmax())

' the'

In [ ]:
input_text = "I like machine learning to"

for i in range(6):
  inputs = tokenizer(input_text, return_tensors="pt").input_ids
  out = model(inputs).logits[0,-1]
  out_word = tokenizer.decode(out.argmax())
  print(out_word)
  input_text = input_text + " " + out_word

input_text

 be
 able
 to
 
 
 


'I like machine learning to  be  able  to      '

In [ ]:
import torch

input_text = "I like machine learning to"

for i in range(6):
    inputs = tokenizer(input_text, return_tensors="pt").input_ids

    logits = model(inputs).logits
    next_token_logits = logits[0, -1, :]   # last position

    next_token_id = torch.argmax(next_token_logits).item()
    next_token = tokenizer.decode([next_token_id])

    input_text += next_token

print(input_text)

I like machine learning to be able to predict the future


In [ ]:
input_text = "I like machine learning to"

k = 10  # consider top 10 candidates
for i in range(6):
    inputs = tokenizer(input_text, return_tensors="pt").input_ids
    logits = model(inputs).logits
    next_token_logits = logits[0, -1, :]
    # get top-k tokens
    top_values, top_indices = torch.topk(next_token_logits, k)
    # convert logits → probabilities
    probs = torch.softmax(top_values, dim=-1)
    # sample from top-k instead of picking max
    sampled_index = torch.multinomial(probs, num_samples=1)
    next_token_id = top_indices[sampled_index].item()
    next_token = tokenizer.decode([next_token_id])
    input_text += next_token
print(input_text)

I like machine learning to be much more flexible and adapt


## sentiment analysis

In [ ]:
from datasets import load_dataset

ds = load_dataset("stanfordnlp/imdb")

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [ ]:
type(ds)

datasets.dataset_dict.DatasetDict

In [ ]:
ds

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [ ]:
ds['train']

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [ ]:
import pandas as pd

In [ ]:
dataset = ds['train'].to_pandas()

dataset

,text,label
0,I rented I AM CURIOUS-YELLOW from my video sto...,0
1,"""I Am Curious: Yellow"" is a risible and preten...",0
2,If only to avoid making this type of film in t...,0
3,This film was probably inspired by Godard's Ma...,0
4,"Oh, brother...after hearing about this ridicul...",0
...,...,...
24995,A hit at the time but now better categorised a...,1
24996,I love this movie like no other. Another time ...,1
24997,This film and it's sequel Barry Mckenzie holds...,1
24998,'The Adventures Of Barry McKenzie' started lif...,1


In [ ]:
from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [ ]:
text = "I really love machine learning!"

result = classifier(text)
print(result)

[{'label': 'POSITIVE', 'score': 0.9998010993003845}]


In [ ]:
text = "This day is terrible"

result = classifier(text)
print(result)

[{'label': 'NEGATIVE', 'score': 0.9995707869529724}]


In [ ]:
print(dataset.iloc[256].text)
print(dataset.iloc[256].label)
print("---------------------------------")
result = classifier(dataset.iloc[256].text)
print(result)

The plot line of No One Sleeps is not a bad idea, and the subject matter is of quite a bit of interest. But, throughout watching this film, we were saying aloud, "These filmmakers go to the trouble of finding good locations, the lighting is good, makeup and hair are good...why is the sound so bad?" Throughout the film the sound was echoy, garbled and much of the dialog was unintelligible.<br /><br />There is some good acting in this film, and I think Jim Thalman is really a good actor. This story, with some of the same actors, would have been worth doing as a high-budget film.<br /><br />I just can't reiterate enough - if you have a limited budget, dedicate more to good sound. Sound is as much a part of a film as the image, and it's worth doing right. Could've earned a 6.
0
---------------------------------
[{'label': 'NEGATIVE', 'score': 0.6596469879150391}]


## ner

In [3]:
from transformers import pipeline

pipe = pipeline("token-classification", model="dslim/bert-base-NER")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/829 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  | 
-------------------------+------------+--+-
bert.pooler.dense.bias   | UNEXPECTED |  | 
bert.pooler.dense.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


tokenizer_config.json:   0%|          | 0.00/59.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [5]:
sentece = "Elon Musk founded SpaceX and Tesla in the United States."

pipe(sentece)

[{'entity': 'B-PER',
  'score': np.float32(0.5674166),
  'index': 1,
  'word': 'El',
  'start': 0,
  'end': 2},
 {'entity': 'I-ORG',
  'score': np.float32(0.42147562),
  'index': 2,
  'word': '##on',
  'start': 2,
  'end': 4},
 {'entity': 'I-PER',
  'score': np.float32(0.9046217),
  'index': 3,
  'word': 'Mu',
  'start': 5,
  'end': 7},
 {'entity': 'I-PER',
  'score': np.float32(0.6375317),
  'index': 4,
  'word': '##sk',
  'start': 7,
  'end': 9},
 {'entity': 'B-ORG',
  'score': np.float32(0.9993874),
  'index': 6,
  'word': 'Space',
  'start': 18,
  'end': 23},
 {'entity': 'I-ORG',
  'score': np.float32(0.9991455),
  'index': 7,
  'word': '##X',
  'start': 23,
  'end': 24},
 {'entity': 'B-ORG',
  'score': np.float32(0.9980107),
  'index': 9,
  'word': 'Te',
  'start': 29,
  'end': 31},
 {'entity': 'I-ORG',
  'score': np.float32(0.991529),
  'index': 10,
  'word': '##sla',
  'start': 31,
  'end': 34},
 {'entity': 'B-LOC',
  'score': np.float32(0.99967396),
  'index': 13,
  'word': 'Un